#!/usr/bin/env bash
# OVTools installer for OpenShift
# Usage: bash install.sh

set -euo pipefail

NAMESPACE="ovtools"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${SCRIPT_DIR}/deployment.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# Check dependencies
for cmd in oc openssl; do
  command -v "$cmd" &>/dev/null || error "'$cmd' not found. Please install it and try again."
done

# Check OpenShift login
info "Checking OpenShift authentication..."
oc whoami &>/dev/null || error "Not logged into an OpenShift cluster. Run 'oc login' first."
CLUSTER=$(oc whoami --show-server)
USER=$(oc whoami)
info "Logged in as '${USER}' on ${CLUSTER}"

# Confirm
echo ""
echo "This will install OVTools in namespace '${NAMESPACE}'."
read -r -p "Continue? [y/N] " confirm
[[ "${confirm,,}" == "y" ]] || { warn "Aborted."; exit 0; }
echo ""

# Apply manifest (without the placeholder secret value)
info "Applying deployment manifest..."
APPLY_OUTPUT=$(oc apply -f "${MANIFEST}" 2>&1) || APPLY_EXIT=$?
echo "${APPLY_OUTPUT}"

# Detect the most common upgrade snag: spec.selector on Deployment is
# immutable, so older installs with a different selector cause apply to fail.
# When we see that specific error, offer to recreate just the Deployment
# (everything else, like SA, RBAC, secrets and route, is preserved).
if [[ "${APPLY_EXIT:-0}" -ne 0 ]]; then
  if echo "${APPLY_OUTPUT}" | grep -q 'spec.selector.*field is immutable'; then
    echo ""
    warn "Existing OVTools deployment has a selector incompatible with this version."
    warn "Kubernetes does not allow changing 'spec.selector' on a Deployment."
    echo ""
    read -r -p "Delete the existing Deployment and recreate it? Other resources will be kept. [y/N] " replace
    if [[ "${replace,,}" == "y" ]]; then
      info "Deleting existing Deployment..."
      oc delete deployment ovtools -n "${NAMESPACE}" --ignore-not-found=true
      info "Re-applying manifest..."
      oc apply -f "${MANIFEST}"
    else
      error "Aborted. Run 'oc delete deployment ovtools -n ${NAMESPACE}' manually if you wish to retry."
    fi
  else
    error "oc apply failed. See output above."
  fi
fi

# Generate and apply cookie secret (must be exactly 32 bytes)
info "Generating cookie secret..."
SECRET=$(openssl rand -base64 24 | tr -d '\n')
oc patch secret ovtools-oauth-cookie-secret -n "${NAMESPACE}" \
  --type=merge -p "{\"stringData\":{\"cookie-secret\":\"${SECRET}\"}}"
info "Cookie secret applied."

# Wait for TLS cert to be generated by OpenShift
info "Waiting for TLS certificate to be generated..."
for i in $(seq 1 12); do
  oc get secret ovtools-tls -n "${NAMESPACE}" &>/dev/null && break
  [[ $i -eq 12 ]] && error "Timed out waiting for ovtools-tls secret. Check OpenShift service CA operator."
  sleep 5
done
info "TLS certificate ready."

# Restart deployment to pick up the secret
info "Restarting deployment..."
oc rollout restart deployment/ovtools -n "${NAMESPACE}"

# Wait for rollout
info "Waiting for rollout to complete..."
oc rollout status deployment/ovtools -n "${NAMESPACE}" --timeout=120s

# Print route
echo ""
ROUTE=$(oc get route ovtools -n "${NAMESPACE}" -o jsonpath='{.spec.host}' 2>/dev/null || echo "")
if [[ -n "${ROUTE}" ]]; then
  info "OVTools is available at: https://${ROUTE}"
else
  warn "Could not retrieve route URL. Run: oc get route ovtools -n ${NAMESPACE}"
fi
