#!/usr/bin/env bash
# OVTools uninstaller for OpenShift
# Removes the resources install.sh creates, and nothing else.
# Usage: bash uninstall.sh [-y] [--delete-namespace]
#   -y, --yes            skip the confirmation prompt
#   --delete-namespace   also delete the 'ovtools' namespace once it is empty
#   -h, --help           show this help

set -euo pipefail

NAMESPACE="ovtools"
ASSUME_YES=0
DELETE_NS=0

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# del removes a resource but never aborts the uninstall. A missing object, a
# missing resource type (e.g. a cluster with the Console capability disabled),
# or a permission gap is warned about and skipped, so one failure cannot leave a
# half-uninstalled cluster.
del() {
  oc delete "$@" --ignore-not-found=true || warn "Could not delete: $*"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -y|--yes)          ASSUME_YES=1 ;;
    --delete-namespace) DELETE_NS=1 ;;
    -h|--help)
      # Print the leading comment block only (skip the shebang, stop at the
      # first non-comment line).
      awk 'NR==1{next} /^#/{sub(/^# ?/,""); print; next} {exit}' "$0"
      exit 0 ;;
    *) error "Unknown argument: $1" ;;
  esac
  shift
done

# Cluster-scoped resources install.sh creates, all named "ovtools*", so deleting
# them by name touches nothing else on the cluster.
CLUSTER_ROLEBINDINGS=(ovtools-oauth-proxy ovtools-impersonator ovtools-group-reader ovtools-monitoring-view)
CLUSTER_ROLES=(ovtools-group-reader)

# Namespaced resources, deleted by exact name so anything else living in the
# namespace is left alone. ovtools-tls is generated by the service CA, not the
# manifest, so it is listed explicitly.
NS_RESOURCES=(
  "route/ovtools"
  "service/ovtools"
  "deployment/ovtools"
  "serviceaccount/ovtools"
  "secret/ovtools-oauth-cookie-secret"
  "secret/ovtools-tls"
)

# Dependencies
for cmd in oc; do
  command -v "$cmd" &>/dev/null || error "'$cmd' not found. Please install it and try again."
done

info "Checking OpenShift authentication..."
oc whoami &>/dev/null || error "Not logged into an OpenShift cluster. Run 'oc login' first."
info "Logged in as '$(oc whoami)' on $(oc whoami --show-server)"

echo ""
echo "This will delete OVTools from namespace '${NAMESPACE}':"
echo "  - ConsoleLink 'ovtools' (if present)"
echo "  - ClusterRoleBindings: ${CLUSTER_ROLEBINDINGS[*]}"
echo "  - ClusterRole: ${CLUSTER_ROLES[*]}"
echo "  - In namespace ${NAMESPACE}: route, service, deployment, serviceaccount, and the ovtools secrets"
if [[ "${DELETE_NS}" -eq 1 ]]; then
  echo "  - The '${NAMESPACE}' namespace itself"
fi
echo ""
echo "It will NOT delete:"
echo "  - ClusterRole 'system:impersonator' (a standard, possibly shared role; remove it by hand only if OVTools created it)"
echo "  - The standard roles 'system:auth-delegator' and 'cluster-monitoring-view' (only the bindings above are removed)"
if [[ "${DELETE_NS}" -eq 0 ]]; then
  echo "  - The '${NAMESPACE}' namespace (pass --delete-namespace to remove it once empty)"
fi
echo ""

if [[ "${ASSUME_YES}" -ne 1 ]]; then
  # `|| confirm=""` so a closed stdin (non-interactive run without -y) takes the
  # clean abort below instead of tripping set -e. `case` instead of the bash-4
  # `${confirm,,}` so the prompt also works on the bash 3.2 that ships on macOS.
  read -r -p "Continue? [y/N] " confirm || confirm=""
  case "${confirm}" in
    [yY]|[yY][eE][sS]) ;;
    *) warn "Aborted."; exit 0 ;;
  esac
  echo ""
fi

# Cluster-scoped first: the ConsoleLink and the RBAC that outlive the namespace.
# The ConsoleLink type only exists when the cluster has the Console capability,
# so gate on its CRD; otherwise `oc delete consolelink` errors on the missing
# type and would abort the run.
if oc get crd consolelinks.console.openshift.io &>/dev/null; then
  info "Removing the console launcher..."
  del consolelink ovtools
fi

info "Removing cluster role bindings..."
for crb in "${CLUSTER_ROLEBINDINGS[@]}"; do
  del clusterrolebinding "${crb}"
done

info "Removing cluster roles created by OVTools..."
for cr in "${CLUSTER_ROLES[@]}"; do
  del clusterrole "${cr}"
done

# Namespaced resources by exact name.
if oc get namespace "${NAMESPACE}" &>/dev/null; then
  info "Removing resources in namespace '${NAMESPACE}'..."
  for res in "${NS_RESOURCES[@]}"; do
    del "${res}" -n "${NAMESPACE}"
  done

  if [[ "${DELETE_NS}" -eq 1 ]]; then
    info "Deleting namespace '${NAMESPACE}'..."
    del namespace "${NAMESPACE}"
  fi
else
  warn "Namespace '${NAMESPACE}' not found; skipping namespaced resources."
fi

echo ""
info "OVTools uninstall complete."
if [[ "${DELETE_NS}" -eq 0 ]] && oc get namespace "${NAMESPACE}" &>/dev/null; then
  info "The '${NAMESPACE}' namespace was kept. Remove it with: oc delete namespace ${NAMESPACE}"
fi
